"""add analytics columns

Revision ID: 29355a39af2b
Revises: 2549fd75bb9c
Create Date: 2026-07-02 00:31:04.180264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29355a39af2b'
down_revision: Union[str, Sequence[str], None] = '2549fd75bb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # Safely add the new columns to the existing table
    op.add_column('urls', sa.Column('clicks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('urls', sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'last_accessed')
    op.drop_column('urls', 'clicks')
    # ### end Alembic commands ###
