from enum import StrEnum


class ErrorCode(StrEnum):
    URL_NOT_FOUND = "URL_NOT_FOUND"
    DUPLICATE_ALIAS = "DUPLICATE_ALIAS"
    URL_EXPIRED = "URL_EXPIRED"
    INVALID_URL = "INVALID_URL"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"